---
- include_tasks: tasks/epel/{{ ansible_distribution }}.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: tasks/secure/secure-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: tasks/secure/secure-RedHat.yml
  when: ansible_os_family == 'RedHat'
