---
- name: Install RPM key for EPEL repo
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{
     ansible_distribution_major_version }}

- name: Ensure EPEL repository is present.
  when: ansible_distribution == 'RedHat'
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{
     ansible_distribution_major_version }}.noarch.rpm
    state: present
