---
- name: Set sysctl parameters
  sysctl:
    name: "{{ item.parameter }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_items:
    - {parameter: 'net.ipv4.ip_forward', value: '1'}
    - {parameter: 'net.ipv4.conf.all.send_redirects', value: '0'}
    - {parameter: 'net.ipv4.conf.default.send_redirects', value: '0'}