---
- name: Set sysctl parameters
  sysctl:
    name: "{{ item.parameter }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_items:
    - {parameter: 'net.ipv4.ip_forward', value: '1'}
    - {parameter: 'net.ipv4.conf.all.send_redirects', value: '0'}
    - {parameter: 'net.ipv4.conf.default.send_redirects', value: '0'}

- name: Open ports for Wireguard
  ufw:
    rule: allow
    direction: in
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
    comment: Created by Ansible
    state: enabled
    delete: false
  with_items:
    - {port: '{{ wireguard_port }}', proto: 'udp'}
  notify: reload ufw
