---
dependency:
  name: galaxy
lint: |
  set -e
#  yamllint .
#  ansible-lint
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox

platforms:
  - name: test-wg-ubuntu2004
    box: geerlingguy/ubuntu2004
    memory: 1024
    cpus: 1
  - name: test-wg-rocky8
    box: geerlingguy/rockylinux8
    memory: 1024
    cpus: 1
#  - name: test-wg-debian11
#    box: generic/debian11
#  - name: test-wg-ubuntu2204
#    box: alvistack/ubuntu-22.04
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
verifier:
  name: ansible
