---
- name: Verify
  hosts: all
  vars_files:
    - ../../roles/android06.wireguard/vars/main.yml
    - ../../roles/android06.wireguard/defaults/main.yml
  tasks:
    - name: Verify that ipsec is running
      systemd:
        name: wg-quick@{{ wireguard_interface }}
        enabled: true
        state: started
      check_mode: true
      register: wireguard_service
      failed_when: wireguard_service is changed

    - name: Count WireGuard interfaces
      ansible.builtin.shell: |
        set -o errexit
        set -o pipefail
        set -o nounset
        wg | grep "peer: " | wc -l
        exit 0
      args:
        executable: "/bin/bash"
      register: wireguard__interfaces_count
      changed_when: false

    - name: Print WireGuard interface count
      ansible.builtin.debug:
        var: wireguard__interfaces_count.stdout

    - name: There should be at least one Wireguard interface
      ansible.builtin.assert:
        that:
          - "wireguard__interfaces_count.stdout|int > 0"
