---
- name: Restart wireguard
  ansible.builtin.service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when:
    - wireguard__restart_interface
    - not ansible_os_family == 'Darwin'
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"

- name: Syncconf wireguard
  ansible.builtin.shell: |
    set -o errexit
    set -o pipefail
    set -o nounset
    systemctl is-active wg-quick@{{ wireguard_interface | quote }} || systemctl start wg-quick@{{ wireguard_interface | quote }}
    wg syncconf {{ wireguard_interface | quote }} <(wg-quick strip /etc/wireguard/{{ wireguard_interface | quote }}.conf)
    exit 0
  args:
    executable: "/bin/bash"
  when:
    - not wireguard__restart_interface
    - not ansible_os_family == 'Darwin'
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"

- name: reboot system
  reboot:
    msg: "Reboot initiated by Ansible to load new kernel modules"

- name: restart ssh
  service: name=sshd state=restarted enabled=yes

- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes

- name: reload ufw
  service: name=ufw state=restarted enabled=yes

- name: restart firewalld
  command: firewall-cmd --reload

- name: restart wgui
  service: name=wgui state=restarted enabled=yes daemon_reload=true

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart wgui-restart.service
  service: name=wgui-restart.service state=restarted daemon_reload=true

- name: restart wgui-restart.path
  service: name=wgui-restart.path state=restarted enabled=yes daemon_reload=true
